Repository AY2021S1-CS2103T-T09-4/tp, pull requests merged in 2020-10, with the labels that each got.

#44 Organize Darktheme.css
  bin/main/view/DarkTheme.css
  src/main/java/seedu/address/Main.java
  src/main/resources/view/DarkTheme.css
Labels: UI

#57 Import Jfoenix to build.gradle
  build.gradle
Labels: UI

#52 Edit DG to include new proposed features
  docs/DeveloperGuide.md
Labels: Priority.High, documentation, type.DG

#59 Add new deck UI
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: Priority.High, UI, type.DG, type.Function

#61 Ui changed theme to green tea colors
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: UI

#65 Add Leitner psuedocode to Leitner.txt
  src/main/java/seedu/address/Leitner.txt
Labels: type.Function

#72 Fix select command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/deck/NewDeckCommand.java
  src/main/java/seedu/address/logic/commands/deck/SelectDeckCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/deck/UniqueDeckList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDeck.java
  src/main/java/seedu/address/ui/DeckListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DeckListPanel.fxml
  src/main/resources/view/EntryListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: Priority.High, help wanted

#81 Developer guide documentation
  docs/DeveloperGuide.md
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelWordBankDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: documentation

#99 Improve ui
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DeckListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/deck/entry/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/ListCommandTest.java
Labels: enhancement

#102 Edit UG
  docs/UserGuide.md
Labels: type.UG

#104 Edit DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/AddressBook.java
Labels: type.DG

#106 Add Basic(!) flash card system
  src/main/java/seedu/address/logic/commands/play/AnswerCommand.java
  src/main/java/seedu/address/logic/commands/play/PlayCommand.java
  src/main/java/seedu/address/logic/commands/play/StopCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/play/AnswerCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/play/Leitner.java
  src/test/java/seedu/address/logic/commands/deck/NewDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/AddCommandTest.java
Labels: Priority.High

#107 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ArchitectureSequenceDiagram.png
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.DG, type.UG

#109 Add diagram to DG for flashcard
  docs/DeveloperGuide.md
  docs/images/AnswerCommandSequenceDiagram.png
  docs/images/PlayCommandSequenceDiagram.png
Labels: type.DG

#115 Add assertions and logging
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/entry/UniqueEntryList.java
  src/main/java/seedu/address/model/play/Leitner.java
  src/test/java/seedu/address/logic/commands/deck/entry/FindCommandTest.java
Labels: Priority.High

#124 Add leitner helper functions
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/play/Leitner.java
Labels: documentation, enhancement

#126 Edit ug
  docs/UserGuide.md
  docs/images/Placeholder.png
Labels: type.UG

#128 Fix bugs
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: bug

#131 Edit UI
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/logic/commands/play/StopCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/entry/Translation.java
  src/main/java/seedu/address/model/deck/entry/Word.java
  src/main/java/seedu/address/model/play/Leitner.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/panels/QuizPanel.java
  src/main/java/seedu/address/ui/panels/ScorePanel.java
  src/main/java/seedu/address/ui/panels/StartPanel.java
  src/main/resources/images/green_tea_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/QuizPanel.fxml
  src/main/resources/view/StartPanel.fxml
Labels: UI, enhancement

#134 Edit UG
  docs/UserGuide.md
Labels: type.UG

#135 Fix table of contents links
  docs/UserGuide.md
Labels: type.UG

#138 Bug fix for duplicate entries in quiz mode
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/entry/UniqueEntryList.java
  src/main/java/seedu/address/model/play/Leitner.java
Labels: bug

#140 Update readme
  README.md
  docs/images/Ui.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/PlayModeParser.java
  src/main/java/seedu/address/model/play/Score.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/deck/DeckCard.java
  src/main/java/seedu/address/ui/panels/StatisticsPanel.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
Labels: type.docsOthers

#141 Update User Guide
  README.md
  docs/UserGuide.md
  docs/images/Placeholder.png
  docs/images/add-remark/$Remark.png
  docs/images/add-remark/CommandInterface.png
  docs/images/add-remark/ContextMenu.png
  docs/images/add-remark/CreateTest.png
  docs/images/add-remark/GradleRun.png
  docs/images/add-remark/ParserInterface.png
  docs/images/add-remark/RemarkBound.png
  docs/images/add-remark/RemarkComplete.png
  docs/images/add-remark/RemarkFailureOutput.png
  docs/images/add-remark/RemarkHello.png
  docs/images/add-remark/RemarkNotImplemented.png
  docs/images/user-guide/10AddingAnEntry.png
  docs/images/user-guide/11EditingAnEntry.png
  docs/images/user-guide/12DeletingAnEntry.png
  docs/images/user-guide/13PlayAGame.png
  docs/images/user-guide/14StopAGame.png
  docs/images/user-guide/1EmptyGUI.png
  docs/images/user-guide/2EmptyGUIWithAnnotation.png
  docs/images/user-guide/3JapaneseAnimalDeck.png
  docs/images/user-guide/4SelectDeckExample.png
  docs/images/user-guide/5AddEntryExample.png
  docs/images/user-guide/6EditEntryExample.png
  docs/images/user-guide/7CreatingADeck.png
  docs/images/user-guide/8RemovingADeck.png
  docs/images/user-guide/9SelectingADeck.png
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/DarkTheme.css
Labels: type.UG
