Repository AY2021S1-CS2103T-T09-4/tp, pull requests merged in 2020-11, with the labels that each got.

#177 Fix bug
  src/main/java/seedu/address/logic/commands/entry/AddCommand.java
  src/main/java/seedu/address/logic/commands/entry/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/deck/entry/Entry.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/deck/entry/EntryTest.java
Labels: bug

#178 Fix bugs 2
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/deck/RemoveDeckCommand.java
  src/main/java/seedu/address/logic/commands/deck/SelectDeckCommand.java
  src/main/java/seedu/address/logic/commands/entry/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/entry/EditCommand.java
  src/main/java/seedu/address/logic/commands/statistics/StatisticsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: bug

#179 Fix answer command parsing error bug
  .gitignore
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/entry/AddCommand.java
  src/main/java/seedu/address/logic/commands/play/AnswerCommand.java
  src/main/java/seedu/address/logic/parser/PlayModeParser.java
Labels: bug

#180 Fix bugs related to Play and Stop Commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/entry/AddCommand.java
  src/main/java/seedu/address/logic/commands/play/AnswerCommand.java
  src/main/java/seedu/address/logic/commands/play/StopCommand.java
  src/main/java/seedu/address/logic/parser/PlayModeParser.java
Labels: bug

#181 Fix ui long entries
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/logic/commands/entry/FindCommand.java
  src/main/java/seedu/address/logic/commands/entry/ListCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/deck/NewDeckCommandParser.java
  src/main/java/seedu/address/logic/parser/entry/FindCommandParser.java
  src/main/java/seedu/address/model/deck/DeckName.java
  src/main/java/seedu/address/model/deck/entry/Translation.java
  src/main/java/seedu/address/model/deck/entry/Word.java
  src/main/java/seedu/address/ui/panels/QuizPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EntryListCard.fxml
  src/main/resources/view/QuizPanel.fxml
  src/test/java/seedu/address/logic/commands/deck/entry/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/deck/NewDeckCommandParserTest.java
  src/test/java/seedu/address/logic/parser/deck/entry/FindCommandParserTest.java
Labels: UI, bug

#182 Add tests
  docs/UserGuide.md
  docs/images/user-guide/18StatsAllDecks.PNG
  docs/images/user-guide/19StatsOneDeck.PNG
  src/main/java/seedu/address/logic/commands/entry/AddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/deck/NewDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/EditEntryDescriptorTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/deck/DeckNameTest.java
  src/test/java/seedu/address/model/deck/DeckTest.java
  src/test/java/seedu/address/model/deck/entry/UniqueEntryListTest.java
  src/test/java/seedu/address/model/play/ScoreTest.java
  src/test/java/seedu/address/model/play/scoring/BinaryScoringTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: tests, type.UG

#184 Increased Code Quality
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/PlayMode.java
  src/main/java/seedu/address/logic/commands/deck/SelectDeckCommand.java
  src/main/java/seedu/address/logic/commands/entry/AddCommand.java
  src/main/java/seedu/address/logic/commands/entry/EditCommand.java
  src/main/java/seedu/address/logic/commands/play/PlayCommand.java
  src/main/java/seedu/address/logic/commands/play/StopCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/play/Leitner.java
  src/main/java/seedu/address/statistics/Statistics.java
  src/main/java/seedu/address/statistics/StatisticsManager.java
Labels: bug, documentation

#186 Revert tab back to entries after clicking quiz tab
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#188 Add Test and Increase Test Code Quality
  src/main/java/seedu/address/model/play/Leitner.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/LogicTestHelper.java
  src/test/java/seedu/address/logic/commands/play/AnswerCommandTest.java
  src/test/java/seedu/address/logic/commands/play/PlayCommandTest.java
  src/test/java/seedu/address/logic/commands/play/StopCommandTest.java
  src/test/java/seedu/address/model/play/LeitnerTest.java
Labels: tests

#189 Edit UG
  docs/UserGuide.md
Labels: documentation

#191 Add PPP for gabrielsimbingyang
  docs/UserGuide.md
  docs/team/gabrielsimbingyang.md
Labels: type.docsOthers

#194 Fix code quality
  src/main/java/seedu/address/logic/commands/deck/NewDeckCommand.java
  src/main/java/seedu/address/logic/commands/deck/RemoveDeckCommand.java
  src/main/java/seedu/address/logic/commands/deck/SelectDeckCommand.java
  src/main/java/seedu/address/logic/commands/entry/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/deck/DeckName.java
  src/main/java/seedu/address/model/deck/UniqueDeckList.java
  src/main/java/seedu/address/model/deck/entry/UniqueEntryList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/deck/DeckListPanel.java
  src/main/java/seedu/address/ui/panels/QuizPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuizPanel.fxml
  src/test/java/seedu/address/logic/commands/deck/NewDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/deck/entry/EditCommandTest.java
  src/test/java/seedu/address/model/deck/DeckNameTest.java
  src/test/java/seedu/address/model/deck/UniqueDeckListTest.java
  src/test/java/seedu/address/model/deck/entry/EntryTest.java
  src/test/java/seedu/address/model/deck/entry/UniqueEntryListTest.java
  src/test/java/seedu/address/testutil/entry/EntryBuilder.java
  src/test/java/seedu/address/testutil/entry/TypicalEntries.java
Labels: documentation

#200 Update dg
  docs/DeveloperGuide.md
Labels: documentation, type.DG

#204 Add activity diagrams
  docs/diagrams/AnswerCommandActivityDiagram.puml
  docs/diagrams/GeneralizedCommandActivityDiagram.puml
  docs/diagrams/PlayActivityDiagram.puml
  docs/diagrams/SelectActivityDiagram.puml
  docs/images/AnswerCommandActivityDiagram.png
  docs/images/GeneralizedCommandActivityDiagram.png
  docs/images/PlayActivityDiagram.png
  docs/images/SelectActivityDiagram.png
Labels: documentation

#213 Update Dg model component
  docs/DeveloperGuide.md
Labels: type.DG

#214 Update ug
  docs/UserGuide.md
  docs/images/user-guide/10SelectingADeck.png
  docs/images/user-guide/10SelectingADeckBefore.png
  docs/images/user-guide/11SelectingADeckAfter.PNG
  docs/images/user-guide/12AddingAnEntry.png
  docs/images/user-guide/13EditingAnEntry.png
  docs/images/user-guide/14DeletingAnEntryBefore.png
  docs/images/user-guide/15DeletingAnEntryAfter.png
  docs/images/user-guide/16PlayAGame.png
  docs/images/user-guide/17StopAGame.png
  docs/images/user-guide/18HelpWindow.PNG
  docs/images/user-guide/18StatsAllDecks.PNG
  docs/images/user-guide/19StatsAllDecks.PNG
  docs/images/user-guide/19StatsOneDeck.PNG
  docs/images/user-guide/20StatsOneDeck.PNG
Labels: documentation, type.UG

#215 Update FAQ
  docs/UserGuide.md
Labels: type.UG

#218 Edit dg ppp diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddEntrySequenceDiagram.puml
  docs/diagrams/AnswerCommandActivityDiagramTwo.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagramMoreOOP.puml
  docs/images/AddEntryActivityDiagram.png
  docs/images/AddEntrySequenceDiagram.png
  docs/images/AnswerCommandActivityDiagramTwo.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagramMoreOOP.png
Labels: documentation

#231 Update UG
  docs/UserGuide.md
  docs/images/user-guide/11Statistics.PNG
  docs/images/user-guide/19StatsAllDecks.PNG
  docs/images/user-guide/20StatsOneDeck.PNG
  docs/images/user-guide/24StatsAllDecks.PNG
  docs/images/user-guide/25StatsOneDeck.PNG
Labels: type.UG

#250 Make minor DG changes
  docs/DeveloperGuide.md
Labels: type.DG

#251 Update ug
  docs/UserGuide.md
  docs/images/user-guide/10WrongAnswer.PNG
  docs/images/user-guide/1EmptyGUI.png
  docs/images/user-guide/4JapaneseAnimalDeck.PNG
  docs/images/user-guide/5SelectDeckExample.png
  docs/images/user-guide/6AddEntryExample.png
  docs/images/user-guide/7EditEntryExample.png
  docs/images/user-guide/8AdditionalEntriesJapanese.PNG
  docs/images/user-guide/9PlayJapaneseDeck.PNG
Labels: type.UG

#255 Remove names and fix jumplink
  docs/DeveloperGuide.md
Labels: documentation

#265 fix quiz mode bug
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/panels/QuizPanel.java
  src/main/resources/view/MainWindow.fxml
Labels: bug
