Repository AY2021S1-CS2103T-T09-4/tp, pull requests merged in 2020-09, with the labels that each got.

#16 Add use cases to developers guide
  docs/DeveloperGuide.md
  src/main/java/seedu/address/Main.java
Labels: type.DG

#25 Remove prefix for address, tag and phone
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: task

#26 Update Ui.png
  README.md
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/person/Translation.java
  src/main/java/seedu/address/model/person/Word.java
  src/main/resources/view/MainWindow.fxml
Labels: type.docsOthers
